name: Docker Image CI

on:
  push:
    branches: [ gha ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checks out code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ‘16.4’
          registry-url: npm.pkg.github.com
      - name: Install dependencies using a safe clean install
        run: npm ci — ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run: docker build ./v2/uci --secret id=npm,src=$HOMW/.npmrc 

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}